version: 2.1
commands:
  print_pipeline_id:
    description: "Prints the pipeline id to the console"
    steps:
      - run: echo "pipeline_id: ${$CIRCLE_WORKFLOW_ID}"
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > /home/circleci/project/output.txt
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - print_pipeline_id
      - attach_workspace:
          at: /home/circleci/project
      - run: cat /home/circleci/project/output.txt
workflows:
  node-tests:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
