version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: echo "hello world" > output.txt
      - persist_to_workspace:
          root: /home/circleci/project
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run: cat /home/circleci/projectoutput.txt
      - attach_workspace:
          at: /home/circleci/project
workflows:
  node-tests:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
